name: Docker Image CI

on:
  push:
    branches: [ "embednix-ci-build" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: sudo docker build -t bitbake-doc-cn utils/docker

    - name: run_docker
      run: sudo docker run -u $(id -u):$(id -g) -v $(pwd):/workdir --rm bitbake-doc-cn make
