name: Docker Image CI

on:
  push:
    branches: [ "embednix-ci-build" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t bitbake-doc-cn utils/docker

    - name: run_docker
      run: docker run -u $(id -u):$(id -g) -v $(pwd):/bitbake-doc-cn --rm bitbake-doc-cn make clean && make
